services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./uploads:/app/uploads
      - ./devices_db.json:/app/devices_db.json
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

  mediamtx:
    image: bluenviron/mediamtx:1.17.0
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "1935:1935"   # RTMP ingest
      - "8888:8888"   # HLS
      - "8889:8889"   # WebRTC HTTP
      - "8189:8189/udp" # WebRTC ICE/UDP
    volumes:
      - ./mediamtx.yml:/mediamtx.yml